### ISSUE TITLE
update .net

### ISSUE THREAD

**Issue by kasperk81** [replit/nixmodules#413]
https://github.com/replit/nixmodules/blob/fcfb59c42d0054430159ef9989ad40e9e7f9d571/pkgs/modules/dotnet/default.nix#L12-L14

dotnet 7 is out of support https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
v9 will be out soon https://www.dotnetconf.net/

also please install libicu libs package

**Comment by blast-hardcheese** [comment]
A dotnet 8 module has been added and is now live! Does `libicu` need some additional platform-level support, or is it able to be installed as a normal dependency in a repl?

Closing for now, feel free to follow up here and we can reopen if necessary.
